// frontend/components/subscribe/subscribe.jsx
import React from 'react';
require ("./subscribe.scss");

import EmailForm from '../email-form/email-form.jsx';

const Subscribe = () => (
  <section className="bee-subscribe">
    <div className="bee-subscribe-honeycomb-desktop"></div>
    <div className="bee-subscribe-container">
      <h1>Provide us your email to receive the latest news!</h1>
      <EmailForm />
    </div>
  </section>
);

export default Subscribe;

// src/app/subscribe/subscribe.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'bee-subscribe',
  templateUrl: './subscribe.component.html',
  styleUrls: ['./subscribe.component.scss']
})
export class SubscribeComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<section class="subscribe">
  <div id="subscribe"></div>
  <div class="overlay"></div>
  <div class="honeycomb"></div>
  <div class="email-container">
    <p>Provide us your email to receive the latest news!</p>
    <bee-email-form></bee-email-form>
  </div>
</section>
